<a href="https://colab.research.google.com/github/SONY123n/07-3for-loop/blob/main/Numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is a Python library? Why ^o we use Python libraries

In [ ]:
#python library is a collection of pre_written code/functions that we can use to perform specific tasks
#python libraries are used because they our time ,help us to avoid writting code from the scratch

What is the difference between Numpy array and List?

In [ ]:
the main difference between Numpy array and list is that 1)-numpy array onloy stores homogenius data so that it takes less time for excecution
2)-memory location(list can be stored in fragmented memory location(dynamic memory),and array will be stored in a static memory)
mainly because of this two the numpy array faster that numpy list

. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)
print(arr.shape)
print(arr.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
arr[1]

array([5, 6, 7, 8])

In [9]:
arr[1,0]

5

5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [10]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
arr[2]

array([ 9, 10, 11, 12])

In [13]:
arr[2,3]

12


Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [14]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
arr[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

 How can you generate a random 3x3 matrix with values between 0 and 1?

In [26]:
np.random.randint(0,1,(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


Describe the difference between np.random.rand and np.random.randn

In [28]:
np.random.rand(3,3)

array([[0.53720142, 0.18085164, 0.29293099],
       [0.9873914 , 0.29880505, 0.49966897],
       [0.65875027, 0.26157278, 0.41379491]])

In [29]:
np.random.randn(3,3)

array([[ 0.31217541,  1.26317592, -0.58510599],
       [-0.58744931,  0.15156912, -0.22002852],
       [-1.08454333, -1.55611578, -0.92295504]])

In [30]:
#the main difference between np.random.randn amd np.random.rand is that randn will also gives the negative values in array ,but rand will not give any negative values in the array it only positive values



9. Write co^e to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [31]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
a=np.expand_dims(arr,axis=0)

In [38]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [39]:
a.ndim

3

 How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [40]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

 Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [45]:
A=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
A

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [46]:
B=np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [48]:
#index wise multiplication
#this will not happen buz of first A(3,4) and B(3,4) here 3!==4 so multiplication don't take
A*B

In [50]:
A*B.T

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [51]:
A@B.T#matix multiplication

matrix([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])

In [52]:
A+B#matrix addition

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [53]:
B-A#matrix subtraction

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [54]:
B/A#matrix division

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

 Which function in Numpy can be used to swap the byte order of an array?

In [55]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
arr.byteswap()

array([[ 72057594037927936, 144115188075855872, 216172782113783808,
        288230376151711744],
       [360287970189639680, 432345564227567616, 504403158265495552,
        576460752303423488],
       [648518346341351424, 720575940379279360, 792633534417207296,
        864691128455135232]])

 What is the significance of the np.linalg.inv function?

In [65]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [66]:
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#np.linalg.inv will caculate the inverse matrix of the given

What does the np.reshape function do, and how is it used?

In [68]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [70]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [71]:
arr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
#reshape is used to change the number of rows and number of columns
#and also used to flattern the array to 1D


What is broadcasting in Numpy?

In [ ]:
#broad casting is nothing but to speared the data from one array to another
#broad casting will adjust the rows if we provide num of columns and also it will perform wise operations betwwen arrays of diff size