In [1]:
import numpy as np

In [3]:
list=['1','2','3','4','5']
array_list=np.array(object=list)

In [ ]:
n this case, since the elements in list are strings, the array_list is also of string type, specifically 'U1', which represents Unicode characters with a maximum length of 1.

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [7]:
list

['1', '2', '3', '4', '5']

In [23]:
print(array_list.dtype)

<U1


In [49]:
print(type(list))

<class 'list'>


In [51]:
#2

# Print data types of elements in list
for element in list_:
    print(type(element))

# Print data types of elements in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [53]:
#3
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list
for element in list_:
    print(type(element))

# Print data types of elements in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [41]:
#4
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
num_array.shape

(2, 3)

In [45]:
num_array.size

6

In [35]:
#5
zero_matrix=np.zeros((3,3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
#6
import numpy as np

# Create a 5x5 identity matrix using numpy.identity()
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
