<a href="https://colab.research.google.com/github/SONY123n/07-3for-loop/blob/main/numpy_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **numpy**

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
#why numpy
#-mathematical function
#faster
#less memory


In [ ]:
l=[1,2,3,4,5,5,6]#this is the list
#it s heterogenius data structutre


In [ ]:
arr=np.array(l)

In [ ]:
type(np.array(l))#nd means n dimensional array

numpy.ndarray

In [ ]:
#arrays are the way to store the data ,and it stores only same type of data
#it stores homogenius data


In [ ]:
arr.ndim#ndim means to find the dimension s of the array

1

In [ ]:
l1=[1,2,3,4,5.4,"sony"]

In [ ]:
arr1=np.array(l1)
arr1#dtype is given as U32 means nothing but this are only the string formate

array(['1', '2', '3', '4', '5.4', 'sony'], dtype='<U32')

In [ ]:
arr1.ndim

1

In [ ]:
#what i smean by two dimension array
arr2=np.array([[1,2,3],[2,3,4]])
arr2

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr2.ndim

2

In [ ]:
l=[1,2,3,4,4,5,5,6]

In [ ]:
mat=np.matrix(l)
mat

matrix([[1, 2, 3, 4, 4, 5, 5, 6]])

In [ ]:
#how to find the dimensions of array by just seeing the array is as by seeing the brackets which are u

In [ ]:
np.matrix([[[1,2],[2,3],[4,5]]])

ValueError: matrix must be 2-dimensional

In [ ]:
np.array([[[1,2],[2,3],[4,5]]])

array([[[1, 2],
        [2, 3],
        [4, 5]]])

In [ ]:
#more way to convert to array
np.asarray([[[1,2],[2,3],[4,5]]])

array([[[1, 2],
        [2, 3],
        [4, 5]]])

In [ ]:
np.asarray([[[1,2],[2,3],[3,4]]])#convert the input to an ndarray ,but pass ndarray subclass

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [ ]:
mat

matrix([[1, 2, 3, 4, 4, 5, 5, 6]])

In [ ]:
np.asarray(mat)

array([[1, 2, 3, 4, 4, 5, 5, 6]])

In [ ]:
#tuple
t=([1,2,3],[4,5,6])
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=5
type(a)

int

In [ ]:
np.array(a)

array(5)

### **concept of sallow copy**

In [ ]:
l=[1,2,3,4,5,6]
arr=np.array(l)#this is mutable
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
a=arr

In [ ]:
arr[-1]

6

In [ ]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [ ]:
arr[0]=10000

In [ ]:
a#by this as the changing the value of arr[0] then the value of a ia also changed

array([10000,     2,     3,     4,     5,     6])

## **concept of deep copy**

In [ ]:
b=a.copy()
b[0]=2000
b

array([2000,    2,    3,    4,    5,    6])

In [ ]:
a

array([10000,     2,     3,     4,     5,     6])

In [ ]:
#as in the deep copy only copy the data any it points to new memory location ,and also changing the values in copy then onluy changes will done ion that new memory location only not in original memory locatio


there are multiple ways to generating arrays


In [ ]:
#from function
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr.shape#this is in one dimensions so that it gives us as the one row

(6,)

In [ ]:
arr.size

6

In [ ]:
a1=([[1,2,3],[4,4,4],[5,5,5]])
a2=np.array(a1)
a2

array([[1, 2, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [ ]:
a2.shape#means this will give u the number of rows and number of coloumns

(3, 3)

In [ ]:
a2.size

9

In [ ]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
range(5)

range(0, 5)

In [ ]:
m = lambda x: x in range(2)
m(1)

True

In [ ]:
 [i for i in range (5)]

[0, 1, 2, 3, 4]

In [ ]:
list(i for i in range (5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
iterable=(i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromiter(range(5),int)

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring('1, 2 ,3 ,4 ,5',sep=',')#sep is a separtor which separates the values may by the values or may be by this ","

array([1., 2., 3., 4., 5.])

In [ ]:
np.fromstring("sony,naresh,kamala",sep=",")

<ipython-input-61-e2344f8b67eb>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("sony,naresh,kamala",sep=",")


array([], dtype=float64)

In [ ]:
arr

array([10000,     2,     3,     4,     5,     6])

In [ ]:
arr.size

6

In [ ]:
arr.shape

(6,)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
l=[1,2,3,4,"sony"]
arr=np.asarray(l)
arr

array(['1', '2', '3', '4', 'sony'], dtype='<U21')

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
range(5)

range(0, 5)

In [ ]:
list(range(1.0,2.10))#range cannot deal with float value

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [ ]:
np.linspace(1,5,20)#means in between 1,5 it gives us 20 values with eqvivalant values

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [ ]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
b1=np.zeros(5)
b1


array([0., 0., 0., 0., 0.])

In [ ]:
b2=np.zeros((3,4))
b2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b2+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
b2.ndim

2

In [ ]:
b3=np.zeros((3,3,4))
b3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
b3.ndim

3

In [ ]:
b3.shape

(3, 3, 4)

In [ ]:
b3.size

36

In [ ]:
b4=np.zeros((1,3,3,4))#for 4 dimension use 1,3 means 3 dimensions with other dimension
b4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
b4.ndim

4

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr=np.ones((3,4))

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr+3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

why we use zeros and ones means somes times we need to create a n dimensional matrix with all values ones and zeros so that we have the inbulit keywords/func to make the things much easier


## INTERVIEW QUESTION

In [ ]:
1-what is numpy?
2-what is array?
3-what is the differnce between numpy array and the list?
4-how to generate array using numpy
5-

# **advance numpy**

In [ ]:
import numpy as np
arr=np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr+5#this num is added index wise

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*5#num is multipled index wise

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3,4))#this give by some random values in a array

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3,4),int)#int is used to convert the float num into number

array([[4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024]])

In [ ]:
np.empty((3,4),int)

array([[4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024]])

In [ ]:
np.eye(5)#EYE returns a 2D array with ones on diagonal and zeros elsewhere means identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import pandas as pd
#by data type is used to convert the array into a dataframe
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [ ]:
#data frame = multiple rows and multiple columns


In [ ]:
#extra topic
import random#random is module

In [ ]:
#random has many use case like it generates random num

In [ ]:
random.choice([1,2,3,4,5,6])#using this kind of function we can create a game

1

In [ ]:
#random is also a library


In [ ]:
random.choice("sony")

'y'

In [ ]:
random.randrange(1,1000)

281

In [ ]:
random.randrange(1,11)

7

In [ ]:
random.random()

0.733729477961526

In [ ]:
lis=[1,2,3,4,5,6,7,8,9]
random.shuffle(lis)
lis

[8, 3, 2, 7, 4, 6, 9, 5, 1]

In [ ]:
random.uniform(1,10)#num between 1 and 10

3.5499014611579

In [ ]:
np.random.rand(2,3)

array([[0.54693359, 0.37772459, 0.54508687],
       [0.13348129, 0.03056398, 0.76069487]])

In [ ]:
np.random.rand(1)

array([0.53240925])

In [ ]:
np.random.randn(2,3)

array([[ 0.91854159,  1.1466144 ,  0.05664409],
       [-0.85166719,  1.77672888, -0.73876846]])

In [ ]:
np.random.random_sample()

0.1672408790552028

In [ ]:
arr=np.random.randint(1,5,size=(3,4))

In [ ]:
arr

array([[3, 1, 3, 1],
       [2, 1, 2, 1],
       [2, 3, 3, 4]])

In [ ]:
arr.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.reshape(2,6)#we can reshape the array

array([[3, 1, 3, 1, 2, 1],
       [2, 1, 2, 3, 3, 4]])

In [ ]:
arr.reshape(2,1)#array size cannot change that why this will not form

ValueError: cannot reshape array of size 12 into shape (2,1)

In [ ]:
arr.reshape(6,2)

In [ ]:
arr.reshape(4,-1)#when we pass -1 then it manage of getting how many num of columns

array([[3, 1, 3],
       [1, 2, 1],
       [2, 1, 2],
       [3, 3, 4]])

In [ ]:
arr.reshape(-1,4)#for we know number of column and system will manage in num if rows

array([[3, 1, 3, 1],
       [2, 1, 2, 1],
       [2, 3, 3, 4]])

In [ ]:
arr.reshape(-1,-1)#for the reshaping we atleast need to know one dimension either row or colunm

ValueError: can only specify one unknown dimension

In [ ]:
arr.reshape(-1,4)

array([[3, 1, 3, 1],
       [2, 1, 2, 1],
       [2, 3, 3, 4]])

In [ ]:
arr.reshape(12,1).base#base means which points or gives us the original

array([[3, 1, 3, 1],
       [2, 1, 2, 1],
       [2, 3, 3, 4]])

In [ ]:
arr.reshape(2,2,3)

array([[[3, 1, 3],
        [1, 2, 1]],

       [[2, 1, 2],
        [3, 3, 4]]])

In [ ]:
arr.reshape(4,3,1)

array([[[3],
        [1],
        [3]],

       [[1],
        [2],
        [1]],

       [[2],
        [1],
        [2]],

       [[3],
        [3],
        [4]]])

In [ ]:
arr.reshape(1,1,1,1,1,1,1,1,2,2,3)

array([[[[[[[[[[[3, 1, 3],
                [1, 2, 1]],

               [[2, 1, 2],
                [3, 3, 4]]]]]]]]]]])

In [ ]:
list=[1,2,3]
arr=np.array(list)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
arr.ndim

1

In [ ]:
import numpy as np

In [ ]:
arr=np.array((1,12,3,4,5,6,7,8,9))
arr

array([ 1, 12,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
arr1=np.random.randint(1,2,[3,4])
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
arr3 = np.zeros((3, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr4 = np.zeros((1, 1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d +1d
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr1 = np.random.randint(1, 10, (5, 6))
arr1

array([[5, 8, 4, 7, 8, 6],
       [7, 3, 4, 1, 9, 5],
       [1, 7, 1, 1, 4, 7],
       [8, 8, 7, 7, 5, 3],
       [9, 9, 7, 5, 6, 8]])

In [ ]:
arr1 > 5

array([[False,  True, False,  True,  True,  True],
       [ True, False, False, False,  True, False],
       [False,  True, False, False, False,  True],
       [ True,  True,  True,  True, False, False],
       [ True,  True,  True, False,  True,  True]])

In [ ]:
arr1[arr1 > 5]

array([8, 7, 8, 6, 7, 9, 7, 7, 8, 8, 7, 7, 9, 9, 7, 6, 8])

In [ ]:
arr1[arr1 < 5]

array([4, 3, 4, 1, 1, 1, 1, 4, 3])

In [ ]:
arr1[0:2, [0,2]] #0th - 1st row in continuation and 0th and 2nd colum

array([[5, 4],
       [7, 4]])

In [ ]:
#slicing on both rows and column
arr1[0:2, 1:3]

array([[8, 4],
       [3, 4]])

In [ ]:
arr1[2:5]

array([[1, 7, 1, 1, 4, 7],
       [8, 8, 7, 7, 5, 3],
       [9, 9, 7, 5, 6, 8]])

In [ ]:
arr1[2:5, 0:2] #slicing

array([[1, 7],
       [8, 8],
       [9, 9]])

In [ ]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [ ]:
arr2

array([[1, 1, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [ ]:
arr1 + arr2

array([[2, 3, 3],
       [4, 4, 2],
       [3, 4, 3]])

In [ ]:
arr1-arr2

array([[0, 1, 1],
       [0, 0, 0],
       [1, 0, 1]])

In [ ]:
arr1*arr2
#mutiplication of matrix through index

array([[1, 2, 2],
       [4, 4, 1],
       [2, 4, 2]])

In [ ]:
#matrix multiplication
arr1@arr2

array([[ 7,  9,  5],
       [ 7,  8,  5],
       [ 8, 10,  6]])

In [ ]:
arr1 / arr2 #index wise divison

array([[1., 2., 2.],
       [1., 1., 1.],
       [2., 1., 2.]])

In [ ]:
#broad casting

In [ ]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a.shape

(4,)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a=np.array([1,2,3])

In [ ]:
a.T

array([1, 2, 3])

In [ ]:
a=np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [ ]:
a.T#tranpose will only occur in 2D not in 1D

array([[1],
       [2],
       [3]])

In [ ]:
arr+a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [ ]:
a=np.array([1,2,3])
a.T

array([1, 2, 3])

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [ ]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.min(a)

1

In [ ]:
a

array([1, 2, 3])

In [ ]:
np.max(a)

3

In [ ]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 2, 2]])

In [ ]:
np.max(arr1)

2

In [ ]:
arr1.T

array([[1, 2, 2],
       [2, 2, 2],
       [2, 1, 2]])

In [ ]:
arr1.flatten()#reduce higher dimension to 1D


array([1, 2, 2, 2, 2, 1, 2, 2, 2])

In [ ]:
#expand_dims>>expands the array by inserting a new axis

In [ ]:
arr=np.array([[1,2,3,4],[4,5,6,7],[3,3,4,5]])
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 3, 4, 5]])

In [ ]:
np.sum(arr)

47

In [ ]:
np.sum(arr,axis=0)

array([ 8, 10, 13, 16])

In [ ]:
np.sum(arr,axis=1)

array([10, 22, 15])

In [ ]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

In [ ]:
arr1=np.expand_dims(arr,axis=0)
arr1

array([[1, 2, 3, 4]])

In [ ]:
arr2=np.expand_dims(arr,axis=0)
arr2

array([[1, 2, 3, 4]])

In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4],[4,6,4,8]])
arr

array([[1, 2, 3, 4],
       [4, 6, 4, 8]])

In [3]:
arr

array([[1, 2, 3, 4],
       [4, 6, 4, 8]])

In [4]:
a=np.squeeze(arr)
a

array([[1, 2, 3, 4],
       [4, 6, 4, 8]])

In [5]:
arr.ndim

2

In [6]:
a.ndim

2

In [7]:
arr

array([[1, 2, 3, 4],
       [4, 6, 4, 8]])

In [8]:
np.repeat(arr,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 6, 6, 6, 4, 4, 4, 8,
       8, 8])

In [9]:
a=np.array([[1,2],[3,4]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
b=np.repeat(a,2)#repeat will the repeat the values in 1D and slo it only repeat after flattering only

In [12]:
b

array([1, 1, 2, 2, 3, 3, 4, 4])

In [13]:
b.reshape(2,4)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [14]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [15]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [16]:
arr=np.array([[1],[2],[3]])
arr

array([[1],
       [2],
       [3]])

In [17]:
np.roll(arr,2)#this is for clock wise

array([[2],
       [3],
       [1]])

In [20]:
np.roll(arr,-2)#this is for anti clock wise/left shift

array([[3],
       [1],
       [2]])

In [18]:
np.diag(arr)

array([1])

In [19]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.roll(arr,1)

array([[9, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.roll(arr,2)

array([[8, 9, 1],
       [2, 3, 4],
       [5, 6, 7]])

In [25]:
np.roll(arr,-1)

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [26]:
arr1=np.random.randint(1,4,(3,4))
arr2=np.random.randint(1,4,(3,4))

In [27]:
arr1

array([[3, 1, 1, 2],
       [1, 2, 1, 2],
       [1, 1, 3, 1]])

In [28]:
arr2

array([[2, 1, 3, 3],
       [3, 1, 3, 2],
       [2, 2, 3, 3]])

In [29]:
arr1**arr2

array([[ 9,  1,  1,  8],
       [ 1,  2,  1,  4],
       [ 1,  1, 27,  1]])

In [31]:
arr1

array([[3, 1, 1, 2],
       [1, 2, 1, 2],
       [1, 1, 3, 1]])

In [30]:
~arr1#this is called bite wise negation in which it gives actual+1's negation

array([[-4, -2, -2, -3],
       [-2, -3, -2, -3],
       [-2, -2, -4, -2]])

in the above the bite wise negation means 3=011 and for negation add +1 to it then 011+1 it will become 4 but taken as negative

numpy string function

In [32]:
arr=np.array(["sony","naresh","kamala"])
arr

array(['sony', 'naresh', 'kamala'], dtype='<U6')

In [34]:
np.char.title(arr)

array(['Sony', 'Naresh', 'Kamala'], dtype='<U6')

In [35]:
np.char.upper(arr)

array(['SONY', 'NARESH', 'KAMALA'], dtype='<U6')

In [36]:
np.char.capitalize(arr)

array(['Sony', 'Naresh', 'Kamala'], dtype='<U6')

In [37]:
arr

array(['sony', 'naresh', 'kamala'], dtype='<U6')

mathematical functions

In [43]:
arr1=np.random.randint(1,10,(3,4))
arr1

array([[1, 5, 9, 6],
       [1, 3, 1, 9],
       [4, 5, 5, 6]])

In [44]:
np.sin(arr1)

array([[ 0.84147098, -0.95892427,  0.41211849, -0.2794155 ],
       [ 0.84147098,  0.14112001,  0.84147098,  0.41211849],
       [-0.7568025 , -0.95892427, -0.95892427, -0.2794155 ]])

In [45]:
np.cos(arr1)

array([[ 0.54030231,  0.28366219, -0.91113026,  0.96017029],
       [ 0.54030231, -0.9899925 ,  0.54030231, -0.91113026],
       [-0.65364362,  0.28366219,  0.28366219,  0.96017029]])

In [46]:
np.log10(arr1)

array([[0.        , 0.69897   , 0.95424251, 0.77815125],
       [0.        , 0.47712125, 0.        , 0.95424251],
       [0.60205999, 0.69897   , 0.69897   , 0.77815125]])

In [47]:
np.exp(arr)

array([[1.48413159e+02, 1.09663316e+03, 2.71828183e+00, 2.71828183e+00],
       [5.45981500e+01, 7.38905610e+00, 7.38905610e+00, 2.71828183e+00],
       [2.98095799e+03, 5.45981500e+01, 1.48413159e+02, 2.71828183e+00]])

In [48]:
np.mean(arr1)

4.583333333333333

In [49]:
np.max(arr1)

9

In [50]:
np.std(arr1)

2.6601482832520613

In [51]:
np.power(arr1,2)

array([[ 1, 25, 81, 36],
       [ 1,  9,  1, 81],
       [16, 25, 25, 36]])

In [52]:
np.subtract(arr1,2)

array([[-1,  3,  7,  4],
       [-1,  1, -1,  7],
       [ 2,  3,  3,  4]])

In [53]:
np.mod(arr1,2)#this will return element wise reminder

array([[1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 0]])

In [54]:
arr1

array([[1, 5, 9, 6],
       [1, 3, 1, 9],
       [4, 5, 5, 6]])

In [55]:
np.sqrt(arr1)

array([[1.        , 2.23606798, 3.        , 2.44948974],
       [1.        , 1.73205081, 1.        , 3.        ],
       [2.        , 2.23606798, 2.23606798, 2.44948974]])

sort and search# this will only work in 1D not on 2D,3D because this hav eno specific directions

In [56]:
arr=np.array([4,2,3,1,5])
arr

array([4, 2, 3, 1, 5])

In [57]:
np.sort(arr)

array([1, 2, 3, 4, 5])

In [58]:
np.searchsorted(arr,3)#this is giving the index of the elemenh

2

In [59]:
np.searchsorted(arr,6)#this is giving us the index num so that sorted array willl remain as sorted

5

In [60]:
arr1=np.array([0,1,0,3,0,7])
np.count_nonzero(arr1)

3

In [62]:
arr1>0

array([False,  True, False,  True, False,  True])

In [63]:
np.where(arr1>0)

(array([1, 3, 5]),)

In [64]:
np.extract(arr1>0,arr1)

array([1, 3, 7])

In [65]:
arr1

array([0, 1, 0, 3, 0, 7])

In [66]:
arr=np.array([1,2,3,4,4])
arr

array([1, 2, 3, 4, 4])

In [67]:
arr.byteswap()

array([ 72057594037927936, 144115188075855872, 216172782113783808,
       288230376151711744, 288230376151711744])

In [68]:
#matrix is 2D array

In [70]:
import numpy.matlib as nm


In [71]:
nm.zeros(4)

matrix([[0., 0., 0., 0.]])

In [72]:
nm.ones(7)

matrix([[1., 1., 1., 1., 1., 1., 1.]])

In [73]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

numpy linera algebra

In [77]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))


In [78]:
arr1

array([[4, 3, 9],
       [6, 1, 5],
       [8, 8, 3]])

In [79]:
arr2

array([[3, 9, 2],
       [8, 2, 2],
       [8, 1, 9]])

In [80]:
arr1@arr2

array([[108,  51,  95],
       [ 66,  61,  59],
       [112,  91,  59]])

In [81]:
a=np.array([[7,-5,-3],[3,5,1],[5,2,-4]])
a

array([[ 7, -5, -3],
       [ 3,  5,  1],
       [ 5,  2, -4]])

In [82]:
b=np.array([16,-8,0])
b

array([16, -8,  0])

In [83]:
np.linalg.solve(a,b)

array([ 0.79120879, -2.06593407, -0.04395604])

In [84]:
arr1

array([[4, 3, 9],
       [6, 1, 5],
       [8, 8, 3]])

In [85]:
np.linalg.inv(arr1)

array([[-0.13309353,  0.22661871,  0.02158273],
       [ 0.07913669, -0.21582734,  0.12230216],
       [ 0.14388489, -0.02877698, -0.05035971]])

In [86]:
np.linalg.det(arr1)

277.99999999999994